#!/bin/bash

# Basic vars
NAME=fencoder
OPERATION=""
VIDFILE=""
VERBOSE=0

# Encoding vars
SETTINGS_CROP=""

# HDR vars
FOUND_DOVI=0
FOUND_HDR10=0
FOUND_HDR10PLUS=0

# HDR vars

# Print help
print_help() {
    echo "Usage: ${NAME} COMMAND FILE"
    echo
    echo "Commands:"
    echo "  analyze           Analyzes the video file & generates encoding options"
    echo "  encode            Encodes the video file"
}

# Grab CLI opts
set +e
options=$(
    getopt -n ${NAME} \
        -o hv \
        --long help,verbose \
        -- "$@"
)
[ $? -eq 0 ] || {
    echo ; print_help
    exit 1
}
eval set -- "$options"
while true; do
    case $1 in
        -h|--help) print_help ; exit ;;
        -v|--verbose) VERBOSE=1 ; shift ; break ;;
        --) shift ; break ;;
        *) break ;;
    esac
    shift
done

# Grab & check args
OPERATION="$1"
VIDFILE="$2"
if [ "$OPERATION" == "" ]; then
    echo "Please specify a command"
    echo
    print_help
    exit 1
fi
if [ "$OPERATION" != "encode" ] && \
    [ "$OPERATION" != "analyze" ]
then
    echo "${OPERATION}: unknown command"
    echo
    print_help
    exit 1
fi

# Check file
check_file() {
    if [ "$VIDFILE" == "" ]; then
        echo "Please specify a video file"
        exit 1
    fi
    if [ ! -f "$VIDFILE" ]; then
        echo "${VIDFILE}: file not found"
        exit 1
    fi
}

# Check tool requirements
check_requirements() {
    set +e
    which hdr10plus_tool dovi_tool ffmpeg jq >/dev/null
    if [ $? -ne 0 ]; then
        echo "Install required tools:"
        echo "  hdr10plus_tool"
        echo "  dovi_tool"
        echo "  ffmpeg"
        echo "  jq"
        exit 1
    fi
    set -e
}

detect_settings() {
    # Basic settings
    SETTINGS_CROP=$(
        ffmpeg \
            -ss 600 \
            -i "$VIDFILE" \
            -t 20 \
            -vf cropdetect \
            -f null \
            - 2>&1 \
            | awk '/crop/ { print $NF }' \
            | tail -1
    )
}

# Detect HDR
detect_hdr() {
    # FFprobe all metadata for the file
    local probe=$(
        ffprobe -hide_banner \
            -loglevel warning \
            -select_streams v \
            -print_format json \
            -show_frames \
            -read_intervals "%+#1" \
            -show_entries "frame=color_space,color_primaries,color_transfer,side_data_list,pix_fmt" \
            -i "$VIDFILE" \
            2>/dev/null
    )

    # Isolate the types of sidedata we have
    local sidedata=$(
        echo "$probe" | jq \
            '.frames[].side_data_list[].side_data_type' \
            2>/dev/null
    )

    set +e

    # Do we have HDR10 metadata?
    echo "$sidedata" | grep "Mastering display metadata" >/dev/null
    if [ $? -eq 0 ]; then
        # This is a heck of a jq command, so break it up to make it easy to read
        local jq_data=' .frames[].side_data_list[]'
        local jq_meta=' | select(.side_data_type | strings | test("Mastering display metadata"))'
        local jq_map=' | to_entries|map("HDR_\(.key | ascii_upcase)=\"\(.value|tostring)\"")|.[]'

        local hdrvars=$(echo $probe | jq -r "${jq_data}${jq_meta}${jq_map}")

        if [ $? -ne 0 ]; then
            echo "ERROR: Couldn't read HDR10 metadata"
            exit 1
        fi
        eval $hdrvars
    fi

    # Do we have HDR10+ metadata?
    echo "$sidedata" | grep "HDR Dynamic Metadata" >/dev/null
    if [ $? -eq 0 ]; then
        FOUND_HDR10PLUS=1
    fi

    # Do we have Dolby Vision metadata?
    echo "$sidedata" | grep "Dolby Vision Metadata" >/dev/null
    if [ $? -eq 0 ]; then
        FOUND_DOVI=1
    fi

    set -e
}

main() {
    # Sanity checks
    check_requirements
    check_file

    # Analysis
    detect_hdr
}

main
